<?php
session_start();
include('connection.php');

$user_id = $_SESSION['user_id'];
$time = time();
createNewNote($link, $time, $user_id);

function createNewNote($link, $time, $user_id){
    $sql = "INSERT INTO notes (user_id, note, time) VALUES ('$user_id', '', '$time')";
    $result = mysqli_query($link, $sql);
    if(!$result){
        echo 'error';
    }else{
        //this function returns the autogenerated id produced in the last query
        echo mysqli_insert_id($link);
    }
}

?>